ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/local
AVR_TOOLS_DIR = /usr
BOARD_TAG = atmega328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_SKETCHBOOK = /usr/share/arduino

ARDUINO_LIBS = bmp085 hih4030 Wire Wire/utility Ethernet Ethernet/utility SPI Arduino

include /usr/local/arduino/Arduino.mk
